FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /app
COPY requirements.txt /app
RUN pip3 install torch --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
RUN pip install -r requirements.txt --no-cache-dir
WORKDIR /app
COPY . /app

CMD ["python", "server.py"]
