apiVersion: v1
kind: Service
metadata:
  name: milvus-service
spec:
  type: ClusterIP  # 
  selector:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: milvus
    component: standalone 
  ports:
    - protocol: TCP
      port: 19530     # Default port for Milvus
      targetPort: 19530 # Port on which the Milvus pod listens
      # nodePort: 30002